apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: argo-deployment
  template:
    metadata:
      labels:
        app: argo-deployment
    spec:
      containers:
      - name: argo-rollout
        image: argoproj/rollouts-demo:green
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: argo-demo-service
spec:
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: argo-deployment
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: argo-demo-ing
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  argo-demo-service
                port:
                  number: 8080
      host: localhost